package com.github.leoreboucas.pedido;

public enum PedidoStatus {
    AGUARDANDO_POSTAGEM, POSTADO, EM_TRIAGEM, EM_TRANSITO, EM_DISTRIBUICAO, SAIU_PARA_ENTREGA, TENTATIVA_ENTREGA, ENTREGUE, CANCELADO, DEVOLVIDO
}
